
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: VOTEDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5  

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build: ./backend
    container_name: api
    ports:
      - "9898:9898"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PORT: 3306
      DB_PASSWORD: 1234
      DB_NAME: VOTEDB
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend/poll
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mysql-data:
  redis-data:
